// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IkfVyPkQ2oxXVRZLFjBUe8TG6Ndado8',
    appId: '1:387756452759:android:78af91a27475e7b4e6b2d2',
    messagingSenderId: '387756452759',
    projectId: 'dreamlore-app-51321',
    storageBucket: 'dreamlore-app-51321.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRisN9KblK7wANYjZsTSCz27BOqVaHvU',
    appId: '1:387756452759:ios:8ec7ae902d335c32e6b2d2',
    messagingSenderId: '387756452759',
    projectId: 'dreamlore-app-51321',
    storageBucket: 'dreamlore-app-51321.firebasestorage.app',
    androidClientId: '387756452759-rou4fdrhq11tqkcgrgabidsn2i96agfu.apps.googleusercontent.com',
    iosClientId: '387756452759-shddn70qu8b9nio6sa9qb6j3ppekra0i.apps.googleusercontent.com',
    iosBundleId: 'com.bitfuzed.dreamlore',
  );
}
