import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app.dart';
import 'core/device_id.dart';
import 'firebase_options.dart';
import 'providers/providers.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final prefs = await SharedPreferences.getInstance();
  final deviceId = await getOrCreateDeviceId(prefs);

  // Firebase powers sign-in only. Options come from firebase_options.dart
  // (generated by `flutterfire configure`), so this works even where the
  // platform config file is missing. Failure is not fatal: the journal never
  // depends on an account, so start anyway and let the sign-in screen explain
  // what's missing. See SHIP.md § Sign-in.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (_) {
    // Unconfigured: AuthService.isConfigured stays false.
  }

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        deviceIdProvider.overrideWithValue(deviceId),
      ],
      child: const DreamloreApp(),
    ),
  );
}
