import 'dart:async';

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app.dart';
import 'core/telemetry.dart';
import 'core/device_id.dart';
import 'core/theme.dart';
import 'firebase_options.dart';
import 'providers/providers.dart';
import 'ui/motion.dart';
import 'ui/night.dart';
import 'ui/scaffold.dart';
import 'widgets/brand_mark.dart';

Future<void> main() async {
  final binding = WidgetsFlutterBinding.ensureInitialized();
  // Hold the native splash until the first Flutter frame is ready, so the
  // moon on ink never flashes to a blank window in between.
  FlutterNativeSplash.preserve(widgetsBinding: binding);

  // In-widget errors render as a quiet night card rather than Flutter's red
  // (debug) or grey (release) box — the one thing worse than a broken widget
  // is a broken widget that looks like a crash.
  ErrorWidget.builder = (details) => const _BrokenWidget();

  try {
    final prefs = await SharedPreferences.getInstance();
    final deviceId = await getOrCreateDeviceId(prefs);

    // Firebase powers sign-in only. Options come from firebase_options.dart
    // (generated by `flutterfire configure`), so this works even where the
    // platform config file is missing. Failure is not fatal: the journal never
    // depends on an account, so start anyway and let the sign-in screen
    // explain what's missing. See SHIP.md § Sign-in.
    var firebaseReady = false;
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      firebaseReady = true;
    } catch (_) {
      // Unconfigured: AuthService.isConfigured stays false.
    }

    if (firebaseReady) {
      // App Check attests that calls really come from this app, so the API key
      // baked into the APK is not enough on its own to hammer Firebase.
      // Registered but NOT enforced yet: turning enforcement on in the console
      // before real devices are seen passing would lock out every user.
      try {
        await FirebaseAppCheck.instance.activate(
          providerAndroid: kDebugMode
              ? const AndroidDebugProvider()
              : const AndroidPlayIntegrityProvider(),
          providerApple: kDebugMode
              ? const AppleDebugProvider()
              : const AppleAppAttestProvider(),
        );
      } catch (_) {
        // Attestation is a hardening layer, never a gate on starting up.
      }

      // Crash reporting. Off in debug, so local stack traces stay in the
      // console and development never pollutes the production crash list.
      final crashlytics = FirebaseCrashlytics.instance;
      await crashlytics.setCrashlyticsCollectionEnabled(!kDebugMode);
      final presentError = FlutterError.onError;
      FlutterError.onError = (details) {
        presentError?.call(details);
        if (!kDebugMode) crashlytics.recordFlutterFatalError(details);
      };
      // Errors raised outside the widget tree — async gaps, platform channels
      // — never reach FlutterError.onError, so they need their own hook.
      PlatformDispatcher.instance.onError = (error, stack) {
        if (!kDebugMode) crashlytics.recordError(error, stack, fatal: true);
        return true;
      };
      await FirebaseAnalytics.instance.setAnalyticsCollectionEnabled(!kDebugMode);
    }
    // Telemetry stays a no-op unless Firebase actually started, so a failed
    // init degrades to "no analytics" rather than throwing on every event.
    Telemetry.enable(ready: firebaseReady);
    if (firebaseReady) {
    }

    runApp(
      ProviderScope(
        overrides: [
          sharedPreferencesProvider.overrideWithValue(prefs),
          deviceIdProvider.overrideWithValue(deviceId),
        ],
        child: const DreamloreApp(),
      ),
    );
  } catch (e) {
    // Preferences or the device id failing to load is rare (a full disk, a
    // corrupted store) but it used to mean a blank white screen forever.
    runApp(StartupErrorApp(error: e));
  }
  FlutterNativeSplash.remove();
}

/// Shown instead of the app when startup itself failed. Offers the one thing
/// that helps — trying again — and says what to do if it doesn't.
class StartupErrorApp extends StatelessWidget {
  final Object error;
  const StartupErrorApp({super.key, required this.error});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      home: Scaffold(
        backgroundColor: Ob.ink,
        body: NightCanvas(
          child: SafeArea(
            child: Column(
              children: [
                const SizedBox(height: 48),
                const BrandMark(size: 72),
                Expanded(
                  child: EmptyState(
                    icon: Icons.nightlight_round,
                    title: "Dreamlore couldn't wake up",
                    body:
                        'Something on this phone stopped the app from '
                        'starting. Trying again usually works; if not, free '
                        'up a little storage and open it once more.',
                    action: SizedBox(
                      width: 240,
                      child: FilledButton(
                        onPressed: main,
                        child: const Text('Try again'),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

/// A single widget that failed to build. Small, quiet, in the palette.
class _BrokenWidget extends StatelessWidget {
  const _BrokenWidget();

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: Reveal(
        child: Container(
          margin: const EdgeInsets.all(8),
          padding: const EdgeInsets.all(14),
          decoration: BoxDecoration(
            color: Colors.white.withValues(alpha: 0.04),
            borderRadius: BorderRadius.circular(18),
            border: Border.all(color: Colors.white.withValues(alpha: 0.08)),
          ),
          child: const Row(
            children: [
              Icon(Icons.auto_fix_off_rounded, color: Ob.muted, size: 20),
              SizedBox(width: 10),
              Expanded(
                child: Text(
                  "This part couldn't be drawn. The rest of the app is fine.",
                  style: TextStyle(fontSize: 13, color: Ob.muted),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
